<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ciudades = array(
        'BUCARAMANGA'=>21,
        'AGUADA'=>21,
        'ALBANIA'=>21,
        'ARATOCA'=>21,
        'BARBOSA'=>21,
        'BARICHARA'=>21,
        'BARRANCABERMEJA'=>21,
        'BETULIA'=>21,
        'BOLIVAR'=>21,
        'CABRERA'=>21,
        'CALIFORNIA'=>21,
        'CAPITANEJO'=>21,
        'CARCASI'=>21,
        'CEPITA'=>21,
        'CERRITO'=>21,
        'CHARALA'=>21,
        'CHARTA'=>21,
        'CHIMA'=>21,
        'CHIPATA'=>21,
        'CIMITARRA'=>21,
        'CONCEPCION'=>21,
        'CONFINES'=>21,
        'CONTRATACION'=>21,
        'COROMORO'=>21,
        'CURITI'=>21,
        'EL CARMEN DE CHUCURY'=>21,
        'EL GUACAMAYO'=>21,
        'EL PEÑON'=>21,
        'EL PLAYON'=>21,
        'ENCINO'=>21,
        'ENCISO'=>21,
        'FLORIAN'=>21,
        'FLORIDABLANCA'=>21,
        'GALAN'=>21,
        'GAMBITA'=>21,
        'GIRON'=>21,
        'GUACA'=>21,
        'GUADALUPE'=>21,
        'GUAPOTA'=>21,
        'GUAVATA'=>21,
        'GUEPSA'=>21,
        'HATO'=>21,
        'JESUS MARIA'=>21,
        'JORDAN'=>21,
        'LA BELLEZA'=>21,
        'LANDAZURI'=>21,
        'LA PAZ'=>21,
        'LEBRIJA'=>21,
        'LOS SANTOS'=>21,
        'MACARAVITA'=>21,
        'MALAGA'=>21,
        'MATANZA'=>21,
        'MOGOTES'=>21,
        'MOLAGAVITA'=>21,
        'OCAMONTE'=>21,
        'OIBA'=>21,
        'ONZAGA'=>21,
        'PALMAR'=>21,
        'PALMAS DEL SOCORRO'=>21,
        'PARAMO'=>21,
        'PIEDECUESTA'=>21,
        'PINCHOTE'=>21,
        'PUENTE NACIONAL'=>21,
        'PUERTO PARRA'=>21,
        'PUERTO WILCHES'=>21,
        'RIONEGRO'=>21,
        'SABANA DE TORRES'=>21,
        'SAN ANDRES'=>21,
        'SAN BENITO'=>21,
        'SAN GIL'=>21,
        'SAN JOAQUIN'=>21,
        'SAN JOSE DE MIRANDA'=>21,
        'SAN MIGUEL'=>21,
        'SAN VICENTE DE CHUCURI'=>21,
        'SANTA BARBARA'=>21,
        'SANTA HELENA DEL OPON'=>21,
        'SIMACOTA'=>21,
        'SOCORRO'=>21,
        'SUAITA'=>21,
        'SUCRE'=>21,
        'SURATA'=>21,
        'TONA'=>21,
        'VALLE SAN JOSE'=>21,
        'VELEZ'=>21,
        'VETAS'=>21,
        'VILLANUEVA'=>21,
        'ZAPATOCA'=>21,
        'YOPAL'=>26,
        'AGUAZUL'=>26,
        'CHAMEZA'=>26,
        'HATO COROZAL'=>26,
        'LA SALINA'=>26,
        'MANI'=>26,
        'MONTERREY'=>26,
        'NUNCHIA'=>26,
        'OROCUE'=>26,
        'PAZ DE ARIPORO'=>26,
        'PORE'=>26,
        'RECETOR'=>26,
        'SABANALARGA'=>26,
        'SACAMA'=>26,
        'SAN LUIS DE PALENQUE'=>26,
        'TAMARA'=>26,
        'TAURAMENA'=>26,
        'TRINIDAD'=>26,
        'VILLANUEVA'=>26,
        );

        foreach($ciudades as $clave => $valor){
            DB::table('ciudades')->insert([
                'nombre' => $clave,
                'slug' => strtolower(str_replace(" ", "-", eliminar_tildes($clave))),
                'id_departamento' => $valor,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ]);
        }
    }
}
